#import <DOM/Event.idl>

// https://html.spec.whatwg.org/#promiserejectionevent
[Exposed=(Window,Worker)]
interface PromiseRejectionEvent : Event {
    constructor(DOMString type, PromiseRejectionEventInit eventInitDict);

    // FIXME: This is a JS::Promise, not a WebIDL::Promise
    // See https://github.com/whatwg/html/issues/10721
    readonly attribute object promise;
    readonly attribute any reason;
};

dictionary PromiseRejectionEventInit : EventInit {
    // https://github.com/whatwg/html/issues/10721
    required object promise;
    any reason;
};
