name: Nightly Linux

on:
  # Automatically run at the end of every day.
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  # CI matrix - runs the job in lagom-template.yml with different configurations.
  Lagom:
    if: github.repository == 'LadybirdBrowser/ladybird'

    strategy:
      fail-fast: false
      matrix:
        os_name: ['Linux']
        os: [ubuntu-24.04-arm]
        arch: ['arm64']
        build_preset: ['Sanitizer_CI']
        toolchain: ['Clang']
        clang_plugins: [false]

        include:
          - os_name: 'Linux'
            os: ubuntu-24.04
            arch: 'x86_64'
            build_preset: 'Distribution_CI'
            toolchain: 'GNU'
            clang_plugins: false

          - os_name: 'macOS'
            os: macos-15
            arch: 'arm64'
            build_preset: 'Distribution_CI'
            toolchain: 'Clang'
            clang_plugins: false

          - os_name: 'Linux'
            os: ubuntu-24.04-arm
            arch: 'arm64'
            build_preset: 'Distribution_CI'
            toolchain: 'Clang'
            clang_plugins: false

    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      os_name: ${{ matrix.os_name }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      build_preset: ${{ matrix.build_preset }}
      clang_plugins: ${{ matrix.clang_plugins }}
